namespace SharpGlyph {
	public class LanguageSystemTag {
		public static string ToName(string id) {
			switch (id) {
				case "ABA ": return "Abaza";
				case "ABK ": return "Abkhazian";
				case "ACH ": return "Acholi";
				case "ACR ": return "Achi";
				case "ADY ": return "Adyghe";
				case "AFK ": return "Afrikaans";
				case "AFR ": return "Afar";
				case "AGW ": return "Agaw";
				case "AIO ": return "Aiton";
				case "AKA ": return "Akan";
				case "ALS ": return "Alsatian";
				case "ALT ": return "Altai";
				case "AMH ": return "Amharic";
				case "ANG ": return "Anglo-Saxon";
				case "APPH": return "Phonetic transcription—Americanist conventions";
				case "ARA ": return "Arabic";
				case "ARG ": return "Aragonese";
				case "ARI ": return "Aari";
				case "ARK ": return "Rakhine";
				case "ASM ": return "Assamese";
				case "AST ": return "Asturian";
				case "ATH ": return "Athapaskan";
				case "AVR ": return "Avar";
				case "AWA ": return "Awadhi";
				case "AYM ": return "Aymara";
				case "AZB ": return "Torki";
				case "AZE ": return "Azerbaijani";
				case "BAD ": return "Badaga";
				case "BAD0": return "Banda";
				case "BAG ": return "Baghelkhandi";
				case "BAL ": return "Balkar";
				case "BAN ": return "Balinese";
				case "BAR ": return "Bavarian";
				case "BAU ": return "Baulé";
				case "BBC ": return "Batak Toba";
				case "BBR ": return "Berber";
				case "BCH ": return "Bench";
				case "BCR ": return "Bible Cree";
				case "BDY ": return "Bandjalang";
				case "BEL ": return "Belarussian";
				case "BEM ": return "Bemba";
				case "BEN ": return "Bengali";
				case "BGC ": return "Haryanvi";
				case "BGQ ": return "Bagri";
				case "BGR ": return "Bulgarian";
				case "BHI ": return "Bhili";
				case "BHO ": return "Bhojpuri";
				case "BIK ": return "Bikol";
				case "BIL ": return "Bilen";
				case "BIS ": return "Bislama";
				case "BJJ ": return "Kanauji";
				case "BKF ": return "Blackfoot";
				case "BLI ": return "Baluchi";
				case "BLK ": return "Pa’o Karen";
				case "BLN ": return "Balante";
				case "BLT ": return "Balti";
				case "BMB ": return "Bambara (Bamanankan)";
				case "BML ": return "Bamileke";
				case "BOS ": return "Bosnian";
				case "BPY ": return "Bishnupriya Manipuri";
				case "BRE ": return "Breton";
				case "BRH ": return "Brahui";
				case "BRI ": return "Braj Bhasha";
				case "BRM ": return "Burmese";
				case "BRX ": return "Bodo";
				case "BSH ": return "Bashkir";
				case "BSK ": return "Burushaski";
				case "BTI ": return "Beti";
				case "BTS ": return "Batak Simalungun";
				case "BUG ": return "Bugis";
				case "BYV ": return "Medumba";
				case "CAK ": return "Kaqchikel";
				case "CAT ": return "Catalan";
				case "CBK ": return "Zamboanga Chavacano";
				case "CCHN": return "Chinantec";
				case "CEB ": return "Cebuano";
				case "CHE ": return "Chechen";
				case "CHG ": return "Chaha Gurage";
				case "CHH ": return "Chattisgarhi";
				case "CHI ": return "Chichewa (Chewa, Nyanja)";
				case "CHK ": return "Chukchi";
				case "CHK0": return "Chuukese";
				case "CHO ": return "Choctaw";
				case "CHP ": return "Chipewyan";
				case "CHR ": return "Cherokee";
				case "CHA ": return "Chamorro";
				case "CHU ": return "Chuvash";
				case "CHY ": return "Cheyenne";
				case "CGG ": return "Chiga";
				case "CJA ": return "Western Cham";
				case "CJM ": return "Eastern Cham";
				case "CMR ": return "Comorian";
				case "COP ": return "Coptic";
				case "COR ": return "Cornish";
				case "COS ": return "Corsican";
				case "CPP ": return "Creoles";
				case "CRE ": return "Cree";
				case "CRR ": return "Carrier";
				case "CRT ": return "Crimean Tatar";
				case "CSB ": return "Kashubian";
				case "CSL ": return "Church Slavonic";
				case "CSY ": return "Czech";
				case "CTG ": return "Chittagonian";
				case "CUK ": return "San Blas Kuna";
				case "DAN ": return "Danish";
				case "DAR ": return "Dargwa";
				case "DAX ": return "Dayi";
				case "DCR ": return "Woods Cree";
				case "DEU ": return "German";
				case "DGO ": return "Dogri";
				case "DGR ": return "Dogri";
				case "DHG ": return "Dhangu";
				case "DHV ": return "Divehi (Dhivehi, Maldivian)";
				case "DIQ ": return "Dimli";
				case "DIV ": return "Divehi (Dhivehi, Maldivian)";
				case "DJR ": return "Zarma";
				case "DJR0": return "Djambarrpuyngu";
				case "DNG ": return "Dangme";
				case "DNJ ": return "Dan";
				case "DNK ": return "Dinka";
				case "DRI ": return "Dari";
				case "DUJ ": return "Dhuwal";
				case "DUN ": return "Dungan";
				case "DZN ": return "Dzongkha";
				case "EBI ": return "Ebira";
				case "ECR ": return "Eastern Cree";
				case "EDO ": return "Edo";
				case "EFI ": return "Efik";
				case "ELL ": return "Greek";
				case "EMK ": return "Eastern Maninkakan";
				case "ENG ": return "English";
				case "ERZ ": return "Erzya";
				case "ESP ": return "Spanish";
				case "ESU ": return "Central Yupik";
				case "ETI ": return "Estonian";
				case "EUQ ": return "Basque";
				case "EVK ": return "Evenki";
				case "EVN ": return "Even";
				case "EWE ": return "Ewe";
				case "FAN ": return "French Antillean";
				case "FAN0": return "Fang";
				case "FAR ": return "Persian";
				case "FAT ": return "Fanti";
				case "FIN ": return "Finnish";
				case "FJI ": return "Fijian";
				case "FLE ": return "Dutch (Flemish)";
				case "FMP ": return "Fe’fe’";
				case "FNE ": return "Forest Nenets";
				case "FON ": return "Fon";
				case "FOS ": return "Faroese";
				case "FRA ": return "French";
				case "FRC ": return "Cajun French";
				case "FRI ": return "Frisian";
				case "FRL ": return "Friulian";
				case "FRP ": return "Arpitan";
				case "FTA ": return "Futa";
				case "FUL ": return "Fulah";
				case "FUV ": return "Nigerian Fulfulde";
				case "GAD ": return "Ga";
				case "GAE ": return "Scottish Gaelic (Gaelic)";
				case "GAG ": return "Gagauz";
				case "GAL ": return "Galician";
				case "GAR ": return "Garshuni";
				case "GAW ": return "Garhwali";
				case "GEZ ": return "Geez";
				case "GIH ": return "Githabul";
				case "GIL ": return "Gilyak";
				case "GIL0": return "Kiribati (Gilbertese)";
				case "GKP ": return "Kpelle (Guinea)";
				case "GLK ": return "Gilaki";
				case "GMZ ": return "Gumuz";
				case "GNN ": return "Gumatj";
				case "GOG ": return "Gogo";
				case "GON ": return "Gondi";
				case "GRN ": return "Greenlandic";
				case "GRO ": return "Garo";
				case "GUA ": return "Guarani";
				case "GUC ": return "Wayuu";
				case "GUF ": return "Gupapuyngu";
				case "GUJ ": return "Gujarati";
				case "GUZ ": return "Gusii";
				case "HAI ": return "Haitian (Haitian Creole)";
				case "HAL ": return "Halam (Falam Chin)";
				case "HAR ": return "Harauti";
				case "HAU ": return "Hausa";
				case "HAW ": return "Hawaiian";
				case "HAY ": return "Haya";
				case "HAZ ": return "Hazaragi";
				case "HBN ": return "Hammer-Banna";
				case "HER ": return "Herero";
				case "HIL ": return "Hiligaynon";
				case "HIN ": return "Hindi";
				case "HMA ": return "High Mari";
				case "HMN ": return "Hmong";
				case "HMO ": return "Hiri Motu";
				case "HND ": return "Hindko";
				case "HO  ": return "Ho";
				case "HRI ": return "Harari";
				case "HRV ": return "Croatian";
				case "HUN ": return "Hungarian";
				case "HYE ": return "Armenian";
				case "HYE0": return "Armenian East";
				case "IBA ": return "Iban";
				case "IBB ": return "Ibibio";
				case "IBO ": return "Igbo";
				case "IJO ": return "Ijo languages";
				case "IDO ": return "Ido";
				case "ILE ": return "Interlingue";
				case "ILO ": return "Ilokano";
				case "INA ": return "Interlingua";
				case "IND ": return "Indonesian";
				case "ING ": return "Ingush";
				case "INU ": return "Inuktitut";
				case "IPK ": return "Inupiat";
				case "IPPH": return "Phonetic transcription—IPA conventions";
				case "IRI ": return "Irish";
				case "IRT ": return "Irish Traditional";
				case "ISL ": return "Icelandic";
				case "ISM ": return "Inari Sami";
				case "ITA ": return "Italian";
				case "IWR ": return "Hebrew";
				case "JAM ": return "Jamaican Creole";
				case "JAN ": return "Japanese";
				case "JAV ": return "Javanese";
				case "JBO ": return "Lojban";
				case "JCT ": return "Krymchak";
				case "JII ": return "Yiddish";
				case "JUD ": return "Ladino";
				case "JUL ": return "Jula";
				case "KAB ": return "Kabardian";
				case "KAB0": return "Kabyle";
				case "KAC ": return "Kachchi";
				case "KAL ": return "Kalenjin";
				case "KAN ": return "Kannada";
				case "KAR ": return "Karachay";
				case "KAT ": return "Georgian";
				case "KAZ ": return "Kazakh";
				case "KDE ": return "Makonde";
				case "KEA ": return "Kabuverdianu (Crioulo)";
				case "KEB ": return "Kebena";
				case "KEK ": return "Kekchi";
				case "KGE ": return "Khutsuri Georgian";
				case "KHA ": return "Khakass";
				case "KHK ": return "Khanty-Kazim";
				case "KHM ": return "Khmer";
				case "KHS ": return "Khanty-Shurishkar";
				case "KHT ": return "Khamti Shan";
				case "KHV ": return "Khanty-Vakhi";
				case "KHW ": return "Khowar";
				case "KIK ": return "Kikuyu (Gikuyu)";
				case "KIR ": return "Kirghiz (Kyrgyz)";
				case "KIS ": return "Kisii";
				case "KIU ": return "Kirmanjki";
				case "KJD ": return "Southern Kiwai";
				case "KJP ": return "Eastern Pwo Karen";
				case "KJZ ": return "Bumthangkha";
				case "KKN ": return "Kokni";
				case "KLM ": return "Kalmyk";
				case "KMB ": return "Kamba";
				case "KMN ": return "Kumaoni";
				case "KMO ": return "Komo";
				case "KMS ": return "Komso";
				case "KMZ ": return "Khorasani Turkic";
				case "KNR ": return "Kanuri";
				case "KOD ": return "Kodagu";
				case "KOH ": return "Korean Old Hangul";
				case "KOK ": return "Konkani";
				case "KON ": return "Kikongo";
				case "KOM ": return "Komi";
				case "KON0": return "Kongo";
				case "KOP ": return "Komi-Permyak";
				case "KOR ": return "Korean";
				case "KOS ": return "Kosraean";
				case "KOZ ": return "Komi-Zyrian";
				case "KPL ": return "Kpelle";
				case "KRI ": return "Krio";
				case "KRK ": return "Karakalpak";
				case "KRL ": return "Karelian";
				case "KRM ": return "Karaim";
				case "KRN ": return "Karen";
				case "KRT ": return "Koorete";
				case "KSH ": return "Kashmiri";
				case "KSH0": return "Ripuarian";
				case "KSI ": return "Khasi";
				case "KSM ": return "Kildin Sami";
				case "KSW ": return "S’gaw Karen";
				case "KUA ": return "Kuanyama";
				case "KUI ": return "Kui";
				case "KUL ": return "Kulvi";
				case "KUM ": return "Kumyk";
				case "KUR ": return "Kurdish";
				case "KUU ": return "Kurukh";
				case "KUY ": return "Kuy";
				case "KYK ": return "Koryak";
				case "KYU ": return "Western Kayah";
				case "LAD ": return "Ladin";
				case "LAH ": return "Lahuli";
				case "LAK ": return "Lak";
				case "LAM ": return "Lambani";
				case "LAO ": return "Lao";
				case "LAT ": return "Latin";
				case "LAZ ": return "Laz";
				case "LCR ": return "L-Cree";
				case "LDK ": return "Ladakhi";
				case "LEZ ": return "Lezgi";
				case "LIJ ": return "Ligurian";
				case "LIM ": return "Limburgish";
				case "LIN ": return "Lingala";
				case "LIS ": return "Lisu";
				case "LJP ": return "Lampung";
				case "LKI ": return "Laki";
				case "LMA ": return "Low Mari";
				case "LMB ": return "Limbu";
				case "LMO ": return "Lombard";
				case "LMW ": return "Lomwe";
				case "LOM ": return "Loma";
				case "LRC ": return "Luri";
				case "LSB ": return "Lower Sorbian";
				case "LSM ": return "Lule Sami";
				case "LTH ": return "Lithuanian";
				case "LTZ ": return "Luxembourgish";
				case "LUA ": return "Luba-Lulua";
				case "LUB ": return "Luba-Katanga";
				case "LUG ": return "Ganda";
				case "LUH ": return "Luyia";
				case "LUO ": return "Luo";
				case "LVI ": return "Latvian";
				case "MAD ": return "Madura";
				case "MAG ": return "Magahi";
				case "MAH ": return "Marshallese";
				case "MAJ ": return "Majang";
				case "MAK ": return "Makhuwa";
				case "MAL ": return "Malayalam";
				case "MAM ": return "Mam";
				case "MAN ": return "Mansi";
				case "MAP ": return "Mapudungun";
				case "MAR ": return "Marathi";
				case "MAW ": return "Marwari";
				case "MBN ": return "Mbundu";
				case "MBO ": return "Mbo";
				case "MCH ": return "Manchu";
				case "MCR ": return "Moose Cree";
				case "MDE ": return "Mende";
				case "MDR ": return "Mandar";
				case "MEN ": return "Me’en";
				case "MER ": return "Meru";
				case "MFA ": return "Pattani Malay";
				case "MFE ": return "Morisyen";
				case "MIN ": return "Minangkabau";
				case "MIZ ": return "Mizo";
				case "MKD ": return "Macedonian";
				case "MKR ": return "Makasar";
				case "MKW ": return "Kituba";
				case "MLE ": return "Male";
				case "MLG ": return "Malagasy";
				case "MLN ": return "Malinke";
				case "MLR ": return "Malayalam Reformed";
				case "MLY ": return "Malay";
				case "MND ": return "Mandinka";
				case "MNG ": return "Mongolian";
				case "MNI ": return "Manipuri";
				case "MNK ": return "Maninka";
				case "MNX ": return "Manx";
				case "MOH ": return "Mohawk";
				case "MOK ": return "Moksha";
				case "MOL ": return "Moldavian";
				case "MON ": return "Mon";
				case "MOR ": return "Moroccan";
				case "MOS ": return "Mossi";
				case "MRI ": return "Maori";
				case "MTH ": return "Maithili";
				case "MTS ": return "Maltese";
				case "MUN ": return "Mundari";
				case "MUS ": return "Muscogee";
				case "MWL ": return "Mirandese";
				case "MWW ": return "Hmong Daw";
				case "MYN ": return "Mayan";
				case "MZN ": return "Mazanderani";
				case "NAG ": return "Naga-Assamese";
				case "NAH ": return "Nahuatl";
				case "NAN ": return "Nanai";
				case "NAP ": return "Neapolitan";
				case "NAS ": return "Naskapi";
				case "NAU ": return "Nauruan";
				case "NAV ": return "Navajo";
				case "NCR ": return "N-Cree";
				case "NDB ": return "Ndebele";
				case "NDC ": return "Ndau";
				case "NDG ": return "Ndonga";
				case "NDS ": return "Low Saxon";
				case "NEP ": return "Nepali";
				case "NEW ": return "Newari";
				case "NGA ": return "Ngbaka";
				case "NGR ": return "Nagari";
				case "NHC ": return "Norway House Cree";
				case "NIS ": return "Nisi";
				case "NIU ": return "Niuean";
				case "NKL ": return "Nyankole";
				case "NKO ": return "N’Ko";
				case "NLD ": return "Dutch";
				case "NOE ": return "Nimadi";
				case "NOG ": return "Nogai";
				case "NOR ": return "Norwegian";
				case "NOV ": return "Novial";
				case "NSM ": return "Northern Sami";
				case "NSO ": return "Sotho, Northern";
				case "NTA ": return "Northern Tai";
				case "NTO ": return "Esperanto";
				case "NYM ": return "Nyamwezi";
				case "NYN ": return "Norwegian Nynorsk (Nynorsk, Norwegian)";
				case "NZA ": return "Mbembe Tigon";
				case "OCI ": return "Occitan";
				case "OCR ": return "Oji-Cree";
				case "OJB ": return "Ojibway";
				case "ORI ": return "Odia (formerly Oriya)";
				case "ORO ": return "Oromo";
				case "OSS ": return "Ossetian";
				case "PAA ": return "Palestinian Aramaic";
				case "PAG ": return "Pangasinan";
				case "PAL ": return "Pali";
				case "PAM ": return "Pampangan";
				case "PAN ": return "Punjabi";
				case "PAP ": return "Palpa";
				case "PAP0": return "Papiamentu";
				case "PAS ": return "Pashto";
				case "PAU ": return "Palauan";
				case "PCC ": return "Bouyei";
				case "PCD ": return "Picard";
				case "PDC ": return "Pennsylvania German";
				case "PGR ": return "Polytonic Greek";
				case "PHK ": return "Phake";
				case "PIH ": return "Norfolk";
				case "PIL ": return "Filipino";
				case "PLG ": return "Palaung";
				case "PLK ": return "Polish";
				case "PMS ": return "Piemontese";
				case "PNB ": return "Western Panjabi";
				case "POH ": return "Pocomchi";
				case "PON ": return "Pohnpeian";
				case "PRO ": return "Provençal / Old Provençal";
				case "PTG ": return "Portuguese";
				case "PWO ": return "Western Pwo Karen";
				case "QIN ": return "Chin";
				case "QUC ": return "K’iche’";
				case "QUH ": return "Quechua (Bolivia)";
				case "QUZ ": return "Quechua";
				case "QVI ": return "Quechua (Ecuador)";
				case "QWH ": return "Quechua (Peru)";
				case "RAJ ": return "Rajasthani";
				case "RAR ": return "Rarotongan";
				case "RBU ": return "Russian Buriat";
				case "RCR ": return "R-Cree";
				case "REJ ": return "Rejang";
				case "RIA ": return "Riang";
				case "RIF ": return "Tarifit";
				case "RIT ": return "Ritarungo";
				case "RKW ": return "Arakwal";
				case "RMS ": return "Romansh";
				case "RMY ": return "Vlax Romani";
				case "ROM ": return "Romanian";
				case "ROY ": return "Romany";
				case "RSY ": return "Rusyn";
				case "RTM ": return "Rotuman";
				case "RUA ": return "Kinyarwanda";
				case "RUN ": return "Rundi";
				case "RUP ": return "Aromanian";
				case "RUS ": return "Russian";
				case "SAD ": return "Sadri";
				case "SAN ": return "Sanskrit";
				case "SAS ": return "Sasak";
				case "SAT ": return "Santali";
				case "SAY ": return "Sayisi";
				case "SCN ": return "Sicilian";
				case "SCO ": return "Scots";
				case "SEK ": return "Sekota";
				case "SEL ": return "Selkup";
				case "SGA ": return "Old Irish";
				case "SGO ": return "Sango";
				case "SGS ": return "Samogitian";
				case "SHI ": return "Tachelhit";
				case "SHN ": return "Shan";
				case "SIB ": return "Sibe";
				case "SID ": return "Sidamo";
				case "SIG ": return "Silte Gurage";
				case "SKS ": return "Skolt Sami";
				case "SKY ": return "Slovak";
				case "SCS ": return "North Slavey";
				case "SLA ": return "Slavey";
				case "SLV ": return "Slovenian";
				case "SML ": return "Somali";
				case "SMO ": return "Samoan";
				case "SNA ": return "Sena";
				case "SNA0": return "Shona";
				case "SND ": return "Sindhi";
				case "SNH ": return "Sinhala (Sinhalese)";
				case "SNK ": return "Soninke";
				case "SOG ": return "Sodo Gurage";
				case "SOP ": return "Songe";
				case "SOT ": return "Sotho, Southern";
				case "SQI ": return "Albanian";
				case "SRB ": return "Serbian";
				case "SRD ": return "Sardinian";
				case "SRK ": return "Saraiki";
				case "SRR ": return "Serer";
				case "SSL ": return "South Slavey";
				case "SSM ": return "Southern Sami";
				case "STQ ": return "Saterland Frisian";
				case "SUK ": return "Sukuma";
				case "SUN ": return "Sundanese";
				case "SUR ": return "Suri";
				case "SVA ": return "Svan";
				case "SVE ": return "Swedish";
				case "SWA ": return "Swadaya Aramaic";
				case "SWK ": return "Swahili";
				case "SWZ ": return "Swati";
				case "SXT ": return "Sutu";
				case "SXU ": return "Upper Saxon";
				case "SYL ": return "Sylheti";
				case "SYR ": return "Syriac";
				case "SYRE": return "Syriac, Estrangela script-variant (equivalent to ISO 15924 'Syre')";
				case "SYRJ": return "Syriac, Western script-variant (equivalent to ISO 15924 'Syrj')";
				case "SYRN": return "Syriac, Eastern script-variant (equivalent to ISO 15924 'Syrn')";
				case "SZL ": return "Silesian";
				case "TAB ": return "Tabasaran";
				case "TAJ ": return "Tajiki";
				case "TAM ": return "Tamil";
				case "TAT ": return "Tatar";
				case "TCR ": return "TH-Cree";
				case "TDD ": return "Dehong Dai";
				case "TEL ": return "Telugu";
				case "TET ": return "Tetum";
				case "TGL ": return "Tagalog";
				case "TGN ": return "Tongan";
				case "TGR ": return "Tigre";
				case "TGY ": return "Tigrinya";
				case "THA ": return "Thai";
				case "THT ": return "Tahitian";
				case "TIB ": return "Tibetan";
				case "TIV ": return "Tiv";
				case "TKM ": return "Turkmen";
				case "TMH ": return "Tamashek";
				case "TMN ": return "Temne";
				case "TNA ": return "Tswana";
				case "TNE ": return "Tundra Nenets";
				case "TNG ": return "Tonga";
				case "TOD ": return "Todo";
				case "TOD0": return "Toma";
				case "TPI ": return "Tok Pisin";
				case "TRK ": return "Turkish";
				case "TSG ": return "Tsonga";
				case "TSJ ": return "Tshangla";
				case "TUA ": return "Turoyo Aramaic";
				case "TUM ": return "Tulu";
				case "TUL ": return "Tumbuka";
				case "TUV ": return "Tuvin";
				case "TVL ": return "Tuvalu";
				case "TWI ": return "Twi";
				case "TYZ ": return "Tày";
				case "TZM ": return "Tamazight";
				case "TZO ": return "Tzotzil";
				case "UDM ": return "Udmurt";
				case "UKR ": return "Ukrainian";
				case "UMB ": return "Umbundu";
				case "URD ": return "Urdu";
				case "USB ": return "Upper Sorbian";
				case "UYG ": return "Uyghur";
				case "UZB ": return "Uzbek";
				case "VEC ": return "Venetian";
				case "VEN ": return "Venda";
				case "VIT ": return "Vietnamese";
				case "VOL ": return "Volapük";
				case "VRO ": return "Võro";
				case "WA  ": return "Wa";
				case "WAG ": return "Wagdi";
				case "WAR ": return "Waray-Waray";
				case "WCR ": return "West-Cree";
				case "WEL ": return "Welsh";
				case "WLN ": return "Walloon";
				case "WLF ": return "Wolof";
				case "WTM ": return "Mewati";
				case "XBD ": return "Lü";
				case "XKF ": return "Khengkha";
				case "XHS ": return "Xhosa";
				case "XJB ": return "Minjangbal";
				case "XOG ": return "Soga";
				case "XPE ": return "Kpelle (Liberia)";
				case "YAK ": return "Sakha";
				case "YAO ": return "Yao";
				case "YAP ": return "Yapese";
				case "YBA ": return "Yoruba";
				case "YCR ": return "Y-Cree";
				case "YIC ": return "Yi Classic";
				case "YIM ": return "Yi Modern";
				case "ZEA ": return "Zealandic";
				case "ZGH ": return "Standard Moroccan Tamazight";
				case "ZHA ": return "Zhuang";
				case "ZHH ": return "Chinese, Hong Kong SAR";
				case "ZHP ": return "Chinese Phonetic";
				case "ZHS ": return "Chinese Simplified";
				case "ZHT ": return "Chinese Traditional";
				case "ZND ": return "Zande";
				case "ZUL ": return "Zulu";
				case "ZZA ": return "Zazaki";
			}
			return id;
		}
	}
}
