namespace SharpGlyph {
	public class TypographyVendors {
		public static string ToName(string id) {
			switch (id.Trim()) {
				// [0-9, !$…]
				case "!ETF": return "!Exclamachine Type Foundry";
				case "$pro": return "CheapProFonts";
				case "100": return "AUTHENTIC";
				case "0264": return "Patricia Lillie";
				case "1ASC": return "Ascender Corporation";
				case "1BOU": return "Boutros International";
				case "1KTF": return "Kief Type Foundry";
				case "2DLT": return "2D Typo";
				case "2REB": return "2Rebels";
				case "39BC": return "Finley's Barcode Fonts";
				case "3ip": return "Three Islands Press";
				case "4FEB": return "4th february";
				case "5PTS": return "Five Points Technology";
				case "72PT": return "72 Puntos";
				case "918": return "RavenType";

				// A
				case "A&S": return "Art&Sign Studio";
				case "A2": return "A2-Type";
				case "aaff": return "AstroAcademia Font Foundry";
				case "AA": return "Alireza Alipour";
				case "AAT": return "AhmetAltunType";
				case "ABBO": return "Arabic Dictionary Lab";
				case "ABC": return "Altek Instruments";
				case "ABCD": return "Dinamo Typefoundry";
				case "ABOU": return "Aboutype, Inc.";
				case "ABYM": return "ABYME";
				case "ACUT": return "Acute Type";
				case "Adam": return "Adam Jagosz";
				case "ADBE": return "Adobe";
				case "ADBO": return "Adobe";
				case "ADG": return "Apply Design Group";
				case "AES": return "AE Type";
				case "AEF": return "Altered Ego Fonts";
				case "AGFA": return "Monotype Imaging (replaced by MONO)";
				case "AID": return "Artistic Imposter Design";
				case "AJL": return "Alex John Lucas";
				case "AJPT": return "Alan Jay Prescott Typography";
				case "AKOF": return "AKOFAType";
				case "ALFA": return "Alphabets";
				case "ALPH": return "Alphameric Broadcast Solutions Limited";
				case "ALPN": return "Alpona Portal";
				case "AL": return "Alessio Laiso Type";
				case "ALIF": return "Alif Type";
				case "ALS": return "Art. Lebedev Studio";
				case "alte": return "Altemus";
				case "ALTS": return "Altsys / Made with Fontographer";
				case "amcs": return "Amit soni";
				case "AMUT": return "Kwesi Amuti";
				case "ANDO": return "Osam Ando";
				case "ANRT": return "Atelier National de Recherche Typographique";
				case "anty": return "Anatoletype";
				case "AOP": return "an Art Of Pengwyn";
				case "APLY": return "Apply Interactive";
				case "APOS": return "Apostrophic Laboratories";
				case "APPL": return "Apple";
				case "ARBX": return "Arabetics";
				case "ARCH": return "Architext";
				case "ARIN": return "Aring Typeface AB";
				case "ARMA": return "Arman Khorramak";
				case "ARPH": return "Arphic Technology Co.";
				case "ARRW": return "Arrow Type";
				case "ARS": return "EN ARS Ltd.";
				case "ART": return "Alex Rosario Type";
				case "ARTE": return "Artegra";
				case "ArTy": return "Archive Type";
				case "AS": return "Alex Slobzheninov";
				case "ASL": return "Abneil Software Ltd fonts";
				case "ASSA": return "astype";
				case "ASYM": return "Applied Symbols";
				case "ATEC": return "Page Technology Marketing, Inc.";
				case "ATF": return "American Type Founders Collection";
				case "ATF1": return "Australian Type Foundry";
				case "ATFS": return "Andrew Tyler's fonts";
				case "AUH": return "Atelier Ursula Heilig SGD";
				case "AURE": return "Aure Font Design";
				case "AUTO": return "Autodidakt";
				case "AVFF": return "Agustín Varela Font Factory";
				case "AVP": return "Aviation Partners";
				case "AZLS": return "Azalea Software, Inc.";

				// B
				case "B&H": return "Bigelow & Holmes";
				case "BARS": return "CIA (BAR CODES) UK";
				case "BASE": return "Baseline Fonts";
				case "BAT": return "BUREAU DES AFFAIRES TYPOGRAPHIQUES";
				case "BBTY": return "Bruno Bernard Typographie";
				case "BCP": return "Expert Labels Ltd.";
				case "BEN": return "Ben Hodosi";
				case "BERT": return "Berthold";
				case "BF": return "BrassFonts";
				case "bftr": return "Bleed Design Studio";
				case "BGDN": return "Ryan Bugden";
				case "bgtl": return "bigital";
				case "BIRD": return "Magpie Paper Works";
				case "BITM": return "Bitmap Software";
				case "BITS": return "Bitstream";
				case "bizf": return "Bizfonts.com";
				case "BL": return "Binnenland";
				case "BLAB": return "BaseLab";
				case "BLAH": return "Mister Bla's Fontworx";
				case "BLCK": return "Black Foundry";
				case "BLI": return "Blissym Language Institute";
				case "BLV": return "Bladvulling";
				case "BLZT": return "Blaze Type";
				case "BMD": return "Brittney Murphy Design";
				case "BNFF": return "BengalFonts";
				case "BOLD": return "Bold Monday";
				case "BORW": return "em2 Solutions";
				case "BOYB": return "BoyBeaver Fonts";
				case "BRBT": return "Bureau Brut";
				case "BRDV": return "BoardVantage, Inc.";
				case "BREM": return "Mark Bremmer";
				case "BROS": return "Michael Brosnan";
				case "BRTC": return "ITSCO - Bar Code Fonts";
				case "BS": return "Barcodesoft";
				case "BST": return "Bolorsoft LLC";
				case "BSTD": return "Bastard Type Inc";
				case "BSYV": return "Ben Syverson";
				case "BUBU": return "BUBULogix";
				case "BWFW": return "B/W Fontworks";
				case "BwT": return "Branding with Type";

				// C
				case "C&B": return "Coppers & Brasses";
				case "C&C": return "Carter & Cone";
				case "C&G": return "C&G Inc.";
				case "C21": return "Club 21";
				case "CAK": return "pluginfonts.com";
				case "CAM": return "Camelot Typefaces";
				case "camp": return "Campotype";
				case "CANO": return "Canon";
				case "CASL": return "H.W. Caslon & Company Ltd.";
				case "CATG": return "CAT-Fonts Germany";
				case "CAVE": return "Fonderia Cavedoni";
				case "CB": return "Christian Büning";
				case "CBDO": return "Borges Lettering & Design";
				case "CDAC": return "Centre for Development of Advanced Computing";
				case "cdd": return "Crazy Diamond Design";
				case "CDFP": return "VT2000 Technical Services";
				case "CELB": return "Celebrity Fontz";
				case "CF": return "Colophon Foundry";
				case "CFA": return "Computer Fonts Australia";
				case "CFAB": return "Creative Fabrica";
				case "CFF": return "Characters Font Foundry";
				case "CJCJ": return "Creative Juncture";
				case "CJT": return "CJ Type";
				case "CKTP": return "CakeType";
				case "CLM": return "Culmus Project";
				case "CMJK": return "Slanted Hall";
				case "COFO": return "Contrast Foundry";
				case "COMI": return "Comicraft";
				case "COMM": return "Commercial Type";
				case "CONR": return "Connare.com";
				case "COOL": return "Cool Fonts";
				case "CORD": return "corduroy";
				case "CR8": return "CR8 Software Solutions";
				case "CRRT": return "Carrot Type";
				case "CT": return "CastleType";
				case "CTDL": return "China Type Designs Ltd.";
				case "CTL": return "Chaitanya Type Library";
				case "cwwf": return "Computers World Wide/AC Capital Funding";
				case "CYPE": return "Club Type";
				case "CYRE": return "Cyreal";
				case "CZOO": return "Creative ZOO";

				// D
				case "D&ST": return "Dots&Stripes Type";
				case "DADA": return "Dada Studio";
				case "DAMA": return "Dalton Maag Limited";
				case "DARK": return "Out Of The Dark";
				case "DB": return "Daniel Bruce";
				case "DBFF": return "DesignBase";
				case "DD": return "Devon DeLapp";
				case "DDT": return "DosDiez Type";
				case "Deco": return "DecoType (replaced by DT)";
				case "DELV": return "Delve Fonts";
				case "dezc": return "Dezcom";
				case "DFS": return "Datascan Font Service Ltd";
				case "DG": return "Daniel Grumer";
				case "DGL": return "Digital Graphic Labs foundry";
				case "DHRM": return "Dharma Type";
				case "DIFO": return "Digital Foundry";
				case "djr": return "DJR";
				case "DNF": return "Deranged Neko Foundry";
				case "DOM": return "Dukom Design";
				case "DR": return "Dmitry Rastvortsev";
				case "DS": return "Dainippon Screen Mfg. Co., Inc.";
				case "DSBV": return "Datascan bv";
				case "DSCI": return "Design Science Inc.";
				case "DSGN": return "DizajnDesign";
				case "DSKY": return "Jacek Dziubinski";
				case "DSSR": return "Dresser Johnson";
				case "DSST": return "Dubina Nikolay";
				case "DST": return "DSType";
				case "DSTE": return "Dieste";
				case "DT": return "DecoType";
				case "DTC": return "Digital Typeface Corp.";
				case "DTF": return "Dunwich Type Founders";
				case "DTIL": return "Detail Type Foundry";
				case "DTL": return "Dutch Type Library";
				case "DTPS": return "DTP-Software";
				case "dtpT": return "dtpTypes Limited";
				case "DUXB": return "Duxbury Systems, Inc.";
				case "DXTF": return "DXTypefoundry";
				case "DYNA": return "DynaComware";

				// E
				case "ECAL": return "ECAL Typefaces";
				case "EDBI": return "edilbiStudio";
				case "EDGE": return "Rivers Edge Corp.";
				case "EF": return "Elsner+Flake";
				case "EFF": return "Electronic Font Foundry";
				case "EFI": return "Elfring Fonts Inc.";
				case "EFNT": return "E Fonts L.L.C.";
				case "EFWS": return "eFilm World";
				case "EKIO": return "Ekioh";
				case "ELSE": return "Elseware";
				case "EMGR": return "Emigre";
				case "EPSN": return "Epson";
				case "ESIG": return "E-Signature";
				case "ETIO": return "Ethiopian Font Foundry";
				case "EVER": return "Evertype";

				// F
				case "FA": return "FontArte Type Foundry";
				case "FAFO": return "FamiraFonts";
				case "FAPA": return "FamiljenPangea";
				case "FAT": return "Fatype";
				case "FBI": return "The Font Bureau, Inc.";
				case "FCAB": return "The Font Cabinet";
				case "FCAN": return "fontage canada";
				case "FCTP": return "Facetype";
				case "FDI": return "FDI fonts.info";
				case "FEED": return "Studio Feed Inc.";
				case "FeoN": return "Feòrag NìcBhrìde";
				case "FGOD": return "FontGod";
				case "FILI": return "Louise Fili Ltd";
				case "FIRA": return "Firasoft Fonts";
				case "FJR": return "F.J.R. German Typeface";
				case "FJTY": return "Frank Jonen - Illustration & Typography";
				case "FMFO": return "Fontmill Foundry";
				case "FMST": return "Formist";
				case "FNSA": return "Fonseca Fonts";
				case "FNTF": return "Fontfoundry";
				case "FoFa": return "FontFabrik";
				case "FoHa": return "The Fonthausen Font Foundry";
				case "FONT": return "Font Source";
				case "FORM": return "Formation Type Foundry";
				case "FOSH": return "Forgotten Shapes";
				case "FOST": return "Foster Type";
				case "FOUN": return "The Foundry";
				case "FP": return "The Fontpad";
				case "FRJN": return "Frere-Jones Type";
				case "FRML": return "formlos";
				case "FRNK": return "Frank Fonts";
				case "FRNZ": return "Franziska Weitgruber";
				case "FRTH": return "Forthcome";
				case "FS": return "Formula Solutions";
				case "FSD": return "Fabrizio Schiavi Design";
				case "FSE": return "Font Source Europe";
				case "FSI": return "FontShop International";
				case "FSL": return "FontSurfer Ltd";
				case "FSLF": return "Fontself";
				case "fsmi": return "Fontsmith";
				case "FSTR": return "Fontstore Pte Ltd";
				case "FTF": return "Fontef";
				case "FTFT": return "FontFont";
				case "FTGD": return "Font Garden";
				case "FTH": return "For the Hearts";
				case "FTN": return "Fountain";
				case "FTPT": return "Fontpartners";
				case "FWD": return "Fontwright Design";
				case "FWKS": return "Fontworks";
				case "FWRE": return "Fontware Limited";
				case "FXTL": return "Foxtail Collectif";
				case "FY": return "Fontyou";

				// G
				case "GAF": return "Glifo Art Fonts Inc.";
				case "GAKU": return "Gakumon";
				case "GALA": return "Galápagos Design Group, Inc.";
				case "GALO": return "Gerald Gallo";
				case "GARI": return "Gary Ritchie";
				case "GATF": return "Greater Albion Typefounders";
				case "GD": return "GD Fonts";
				case "Geez": return "Beteseb Graphic Design";
				case "GF": return "GarageFonts";
				case "GIA": return "Georgian Internet Avenue";
				case "GLCF": return "GLC foundry";
				case "GLYF": return "Glyph Systems";
				case "GNRL": return "General Type Studio";
				case "GNU": return "Free Software Foundation, Inc.";
				case "GOAT": return "Dingbat Dungeon";
				case "GOGO": return "Fonts-A-Go-Go";
				case "GOHE": return "GoHebrew, division of GoME2.com Inc.";
				case "GOOG": return "Google";
				case "GPI": return "Gamma Productions, Inc.";
				case "GRAF": return "Grafikarna d.o.o.";
				case "GRCR": return "Graphicore";
				case "GREY": return "Greyletter";
				case "GRIL": return "Grilled cheese";
				case "GRIM": return "Legacy publishing";
				case "grro": return "grafikk RØren";
				case "GS": return "Grayscale Limited";
				case "GT": return "Graphity!";
				case "GTYP": return "G-Type";

				// H
				case "H": return "Hurme Design";
				case "H&FJ": return "Hoefler & Frere-Jones";
				case "HA": return "HoboArt";
				case "HAD": return "Hoffmann Angelic Design";
				case "Hafo": return "Hafonton";
				case "HAIL": return "Hail Design";
				case "HanS": return "HanStyle";
				case "HAUS": return "TypeHaus";
				case "HEB": return "Sivan Toledo";
				case "HFJ": return "Hoefler & Frere-Jones (replaced by H&FJ)";
				case "HIH": return "HiH Retrofonts";
				case "HILL": return "Hill Systems";
				case "HJZ": return "Hans J. Zinken";
				case "HKSY": return "HAKUSYUFONTS";
				case "HL": return "High-Logic";
				case "HM": return "Haiku Monkey";
				case "HoP": return "House of Pretty";
				case "HOUS": return "House Industries";
				case "HP": return "Hewlett-Packard";
				case "HS": return "HermesSOFT Company";
				case "HT": return "Huerta Tipográfica";
				case "HTF": return "The Hoefler Type Foundry, Inc.";
				case "HU": return "Hungarumlaut";
				case "HVD": return "HVD Fonts GmbH";
				case "HXTP": return "Hexatype";
				case "HY": return "HanYang Information & Communication";

				// I
				case "IBM": return "IBM";
				case "IC": return "Ian J. Cox";
				case "IDAU": return "IDAutomation.com, Inc.";
				case "IDEA": return "Glenn Campbell t/a Idea Studio";
				case "IDEE": return "IDEE TYPOGRAFICA";
				case "IDF": return "International Digital Fonts";
				case "IDMS": return "Incstone Design by Megami Studios";
				case "Idt.": return "Identitype";
				case "IFF": return "Indian Font Factory";
				case "IINF": return "iInformatica Srls";
				case "IKOF": return "IKOffice GmbH";
				case "ILP": return "Indigenous Languages Project";
				case "IMPR": return "Impress";
				case "INGA": return "Inga Type";
				case "INGT": return "Ingrimayne Type";
				case "INRA": return "INRAY Inc.";
				case "INTF": return "Interfont";
				case "INTR": return "Interstitial Entertainment";
				case "INVC": return "Invoice Central";
				case "INVD": return "TYPE INVADERS";
				case "INVT": return "Invisible Type";
				case "ISE": return "ISE-Aditi Info. Pvt . Ltd.";
				case "ITC": return "ITC";
				case "ITF": return "Red Rooster Collection (ITF, Inc.)";
				case "ITFO": return "Indian Type Foundry";
				case "ITSM": return "Simon Stratford";
				case "IvyF": return "The Ivy Foundry";
				case "IWA": return "Iwata Corporation";

				// J
				case "J23": return "June 23";
				case "JABM": return "JAB'M Foundry";
				case "JAF": return "Just Another Foundry";
				case "JAKE": return "Jake Tilson Studio";
				case "JBLT": return "JEAN-BAPTISTE LEVÉE TYPOGRAPHY";
				case "JCT": return "Jamie Clarke Type";
				case "JDB": return "Jeff Bensch";
				case "jeff": return "jeff-levine";
				case "JF": return "Jan Fromm";
				case "JHA": return "Jan Henrik Arnold";
				case "JHF": return "JH Fonts";
				case "JLIF": return "jli Foundry – Julie Soudanne";
				case "JOON": return "JoonFont";
				case "JP": return "Jamra Patel";
				case "JPTT": return "Jeremy Tankard Typography Ltd";
				case "JRW": return "Richard Wordingham";
				case "JUST": return "Just in Type";
				case "JVRT": return "Just van Rossum Type";
				case "JWTM": return "Type Matters";
				case "JY": return "JIYUKOBO Ltd.";

				// K
				case "K": return "Kvant Type Foundry";
				case "ka": return "kloeg architecture";
				case "KAME": return "Kame Design";
				case "KATF": return "Kingsley/ATF";
				case "KBNT": return "Kombinat-Typefounders";
				case "KD": return "Kassymkulov Design";
				case "KDW": return "Kinuta Font Factory";
				case "KF": return "Karakta Fonthome";
				case "KHTB": return "Monkey Arts Ltd.";
				case "KILO": return "Kilotype";
				case "KIRK": return "Typekirk";
				case "KLIM": return "Klim Typographic Design";
				case "KLTF": return "Karsten Luecke";
				case "KMRS": return "Mony Sath & Chhit Wornnarith - KhemaraSoft";
				case "KNST": return "Konst.ru";
				case "KNTR": return "Kontour";
				case "KOP": return "Leo Koppelkamm";
				case "KORK": return "Khork OÜ";
				case "KOST": return "Kostic Type Foundry";
				case "KOVL": return "Koval Type Foundry";
				case "KrKo": return "Kreative Software";
				case "KRND": return "Karandash Type & Graphics Foundry";
				case "KTF": return "Kustomtype";
				case "KTRF": return "Kazan Traditional Font";
				case "KUBA": return "Kuba Tatarkiewicz";
				case "KUSH": return "KushJain";

				// L
				case "L2M3": return "L2M3 Kommunikationsdesign GmbH";
				case "LA": return "Large";
				case "LAIT": return "la laiterie";
				case "LAND": return "Typeland";
				case "LANS": return "Lanston Type Company";
				case "LARA": return "Larabiefonts";
				case "LAUD": return "Carolina Laudon";
				case "LAYT": return "LAYOUT SARL";
				case "LBV": return "La Bolde Vita";
				case "LEAF": return "Interleaf, Inc.";
				case "LETR": return "Letraset";
				case "lewd": return "Lettering World LLC";
				case "LFS": return "Letters from Sweden";
				case "LGFF": return "LIPIGHOR FONT FOUNDRY";
				case "LGX": return "Logix Research Institute, Inc.";
				case "LHF": return "Letterhead Fonts";
				case "LIND": return "Lindenberg Software LLC";
				case "LING": return "Linguist's Software";
				case "LINK": return "Linkpen Handwriting Fonts";
				case "LINO": return "Linotype GmbH";
				case "LIVE": return "Livedesign";
				case "LJ": return "Letterjuice";
				case "LLDL": return "La Lettre de Luxe";
				case "LNGU": return "LangusteFonts";
				case "LNTO": return "Lineto";
				case "lool": return "lo-ol Type";
				case "LORO": return "LoRo Productions";
				case "LOU": return "Lou Type Foundry";
				case "LP": return "LetterPerfect Fonts";
				case "LT": return "Le Typophage";
				case "LTF": return "Liberty Type Foundry";
				case "LTFD": return "Linnea Type";
				case "Ltrm": return "Lettermin type and design";
				case "LTRX": return "Lighttracks";
				case "LTTR": return "LettError";
				case "LuAn": return "Patrice Provost";
				case "LUD": return "Ludlow";
				case "LuFo": return "LucasFonts";
				case "LUSH": return "Lush Type";
				case "LUV": return "iLUVfonts";

				// M
				case "M+F": return "Measure + Fit";
				case "MACR": return "Macromedia / Made with Fontographer";
				case "MADT": return "MADType";
				case "MagD": return "Magus Digital";
				case "MANS": return "Mans Greback AB";
				case "MAPS": return "Tom Mouat's Map Symbol Fonts";
				case "MATE": return "TypeMates";
				case "MATS": return "Match Fonts";
				case "MC": return "Cerajewski Computer Consulting";
				case "MCHL": return "Michal Sahar";
				case "MCKL": return "MCKL";
				case "MCOW": return "Mountaincow";
				case "MDSN": return "Moraitis Design";
				case "MEAP": return "MetaAppz";
				case "MEH": return "Steve Mehallo";
				case "MEIR": return "Meir Sadan";
				case "MESA": return "FontMesa,";
				case "MF": return "Magic Fonts";
				case "MFNT": return "Masterfont";
				case "MG": return "Milieu Grotesque";
				case "MGD": return "Matt Grey Design";
				case "MH": return "Misti’s Fonts";
				case "MHTY": return "Minjoo Ham";
				case "MILL": return "Millan";
				case "MINT": return "Mint Type";
				case "MISS": return "Missy Meyer";
				case "MJ": return "Majus Corporation";
				case "MJR": return "Majur Inc.";
				case "MLAG": return "Michael LaGattuta";
				case "MLBU": return "Malibu Dream Designs, LLC";
				case "MLGC": return "Micrologic Software";
				case "mlss": return "Mark Simonson Studio LLC";
				case "MMFT": return "Michel M.";
				case "MMIK": return "Monomonnik";
				case "MNCK": return "Mine Creek";
				case "mnik": return "Mooniak";
				case "MNJU": return "Manjunatha Bengaluru";
				case "MNKR": return "Monokrom Skriftforlag AS";
				case "MODI": return "Modular Infotech Private Limited.";
				case "MOHT": return "Al Mohtaraf Assaudi Ltd";
				case "MOJI": return "Mojijuku";
				case "MOMI": return "Momentum 18";
				case "MONB": return "Monib";
				case "MONE": return "Meta One Limited";
				case "MONO": return "Monotype Imaging";
				case "MOON": return "Moonlight Type and Technolog";
				case "MOTA": return "Mota Italic";
				case "MRSL": return "Mark Russell";
				case "MRSW": return "Morisawa & Company, Ltd.";
				case "MRV": return "Morovia Corporation";
				case "MS": return "Microsoft Corp.";
				case "MSCH": return "Guitar-Injection";
				case "MSCR": return "Majus Corporation";
				case "MSE": return "MSE-iT";
				case "MSTK": return "Alex Serada";
				case "MT": return "Monotype Imaging (replaced by MONO)";
				case "MTF": return "Miss Tiina Fonts";
				case "MTFO": return "Music Type Foundry";
				case "MTNT": return "Mutant Standard";
				case "MTY": return "Motoya Co. ,LTD.";
				case "MUTF": return "Murasu Systems Sdn. Bhd";
				case "MVB": return "MVB Fonts";
				case "MVTP": return "Mauve Type";
				case "MVty": return "MV Typo";
				case "MW": return "Michael Want";
				case "MYFO": return "MyFonts.com";

				// N
				case "NB": return "No Bodoni Typography";
				case "NBR": return "Noir Blanc Rouge";
				case "ncnd": return "&cond";
				case "NDCT": return "Neufville Digital Corporatype";
				case "NDEF": return "Notdef Type";
				case "NDTC": return "Neufville Digital";
				case "NEC": return "NEC Corporation";
				case "NEW": return "Newlyn";
				case "NICK": return "Nick's Fonts";
				case "NIS": return "NIS Corporation";
				case "NM": return "NM type";
				case "NN": return "NN Type Foundry";
				case "NONO": return "Nouvelle Noire Type Foundry";
				case "NOOT": return "Nootype";
				case "NOPN": return "Noponies";
				case "NorB": return "NorFonts.ma";
				case "NORF": return "Norfok Incredible Font Design";
				case "NOVA": return "NOVATYPE";
				case "NP": return "Nipponia";
				case "NVTF": return "Nova Type Foundry";
				case "NYM": return "Nymark Type";
				case "NYCM": return "NYC Music Services";

				// O
				case "ODSR": return "Oddsorts";
				case "OHG": return "Our House Graphic Design";
				case "OHNO": return "OH no Type Company";
				case "OKAY": return "Okay Type";
				case "OMNI": return "Omnitype";
				case "OMSE": return "OMSETYPE";
				case "Once": return "Michael T Neff";
				case "OPTM": return "Optimo";
				case "OPTO": return "Opto";
				case "OR": return "Or Type";
				case "ORBI": return "Orbit Enterprises, Inc.";
				case "ORK1": return "Ork1";
				case "OSFC": return "Out Of Step Font Company";
				case "OST": return "Orange Slice Type";
				case "OURT": return "Ourtype";

				// P
				case "P22": return "P22 Inc.";
				case "PARA": return "ParaType Inc.";
				case "pbd0": return "Peter Bain";
				case "PBL": return "Publié";
				case "PDWX": return "Parsons Design Workx";
				case "PEAC": return "PeachCreme.com";
				case "PECI": return "Pecita";
				case "PETR": return "Daria Petrova";
				case "PF": return "Phil's Fonts, Inc.";
				case "PHO": return "phospho type foundry";
				case "PHTM": return "Phantom Foundry";
				case "PINT": return "PintassilgoPrints";
				case "PIXL": return "Pixilate";
				case "PKDD": return "Philip Kelly Digital Design";
				case "PLAT": return "PLATINUM technology";
				case "Plau": return "Plau";
				case "PLAY": return "Playtype";
				case "PPPR": return "Pepper Type";
				case "PRFS": return "Production First Software";
				case "PRGR": return "Paragraph";
				case "PRLK": return "Emre Parlak";
				case "PROD": return "Production Type";
				case "PROT": return "PROTOTYPO";
				case "Prox": return "Proxima Software";
				case "PRTF": return "Process Type Foundry";
				case "PSIS": return "PhotoShopIsland.com";
				case "pstu": return "Pseudonym Type Studio";
				case "PSY": return "PSY/OPS";
				case "PT": return "Playtype";
				case "PTF": return "Porchez Typofonderie";
				case "PTMI": return "Page Technology Marketing, Inc.";
				case "PTYP": return "PreussType";
				case "PYRS": return "PYRS Fontlab Ltd. / Made with FontLab";
				case "PYTE": return "The Pyte Foundry";

				// Q
				case "QMSI": return "QMS/Imagen";
				case "QRAT": return "Quadrat Communications";
				case "QTYP": return "Qtypography";

				// R
				case "RARE": return "Rare Bird Font Foundry";
				case "RARI": return "RAR Illustrations";
				case "RDGR": return "Rüdiger";
				case "READ": return "ReadyType";
				case "REAL": return "Underware";
				case "RES": return "Resultat";
				case "RICK": return "Rickner Type";
				case "RIXF": return "FONTRIX Inc.";
				case "RJPS": return "Reall Graphics";
				case "RJST": return "Rob Jelinski Studios, llc.";
				case "RKFN": return "R K Fonts";
				case "RL": return "Ruben Holthuijsen";
				case "RLTF": return "Rebeletter Studios";
				case "RMU": return "RMU TypeDesign";
				case "ROB": return "Robert Janes";
				case "robo": return "Buro Petr van Blokland";
				case "ROBU": return "SC ROBU DESIGN S.R.L.";
				case "ROHH": return "ROHH studio";
				case "RPTR": return "Rampage Raptor";
				case "RRT": return "Red Rooster Collection (ITF, Inc.)";
				case "RSJ": return "RSJ Software";
				case "RSMS": return "Rsms";
				case "RST": return "Rosetta";
				case "RUDY": return "RudynFluffy";
				case "RXBN": return "Roxaboxen";
				case "RYOB": return "Ryobi Limited";
				case "RYT": return "Ra'ey Type";

				// S
				case "S4TF": return "Sed4-Type Foundry";
				case "SAJA": return "Saja Typeworks";
				case "SALT": return "Solonka Type Foundry";
				case "SAND": return "Sandoll";
				case "SAPL": return "Fonderie sans plomb";
				case "SATY": return "Samuelstype Design AB";
				case "SAX": return "s.a.x. Software gmbh";
				case "SbB": return "Sketchbook B";
				case "SBT": return "SelfBuild Type Foundry";
				case "SCTO": return "Schick Toikka";
				case "SE": return "Stéphane Elbaz";
				case "Sean": return "The FontSite";
				case "SFS": return "Sarumadhu Services Pvt. Ltd.";
				case "SFUN": return "Software Union";
				case "SG": return "Scooter Graphics";
				case "SHAM": return "ShamFonts / Shamrock Int.";
				case "SHFT": return "Shift";
				case "SHMI": return "Sharanda";
				case "SHOT": return "Shotype";
				case "SHRP": return "Sharp Type";
				case "SHS": return "Shahab Siavash Studio";
				case "SHUB": return "The Software Hub";
				case "sic": return "Skill Information\"S\" Co., Ltd.";
				case "SIG": return "vLetter, Inc";
				case "SIL": return "SIL International (SIL)";
				case "SIT": return "Summit Information Technologies Pvt.Ltd,";
				case "SKP": return "Essqué Productions";
				case "skz": return "Celtic Lady's Fonts";
				case "SL": return "Silesian Letters";
				case "Slab": return "Schriftlabor";
				case "SMC": return "Swathanthra Malayalam Computing";
				case "SMPJ": return "Senamirmir Project";
				case "SN": return "SourceNet";
				case "SOHO": return "Soft Horizons";
				case "SOS": return "Standing Ovations Software";
				case "SOTY": return "So Type";
				case "SPIR": return "Spiratype";
				case "SPRT": return "Sports Fonts";
				case "spty": return "supertype";
				case "SRC": return "Source Foundry";
				case "STC": return "Sorkin Type Co";
				case "STF": return "Brian Sooy & Co + Sooy Type Foundry";
				case "STFD": return "snuffletrumper";
				case "Stor": return "Storm Type Foundry";
				case "STYP": return "Stone Type Foundry";
				case "SUNW": return "sunwalk fontworks";
				case "SVTD": return "Synthview";
				case "SWFT": return "Swfte International";
				case "SWTY": return "Swiss Typefaces";
				case "SXRA": return "Page42 Type Foundry";
				case "SYDA": return "Shree Muktananda Ashram";
				case "SYN": return "SynFonts";
				case "SYRC": return "Syriac Computing Institute";
				case "SYRF": return "Syrian Revolution font";

				// T
				case "TB": return "TypeBank Co.,Ltd";
				case "TBFF": return "TrueBlue Font Foundry";
				case "TC": return "Typeco";
				case "TCH": return "Darryl Cook";
				case "TD": return "Typedepot";
				case "TDR": return "Tansin A. Darcos & Co.";
				case "TERM": return "Terminal Design, Inc.";
				case "TF": return "Treacyfaces / Headliners";
				case "TF3D": return "TattooFont3D";
				case "TFAC": return "Typefactory";
				case "TFND": return "Typefounding";
				case "TGHT": return "TIGHTYPE";
				case "THIN": return "Thinstroke Design LLC";
				case "TILD": return "Tilde, SIA";
				case "TIMO": return "Tim Romano";
				case "TIMR": return "Tim Rolands";
				case "TINY": return "Tiny Type Co.";
				case "TIPO": return "Tipo";
				case "TIRO": return "Tiro Typeworks";
				case "TJS": return "Typejockeys";
				case "TLIN": return "Teeline Fonts";
				case "TM": return "Type Mafia";
				case "TMF": return "The MicroFoundry";
				case "TMT": return "TypeMyType Comm. V.";
				case "TNB": return "The Northern Block";
				case "TNTY": return "tntypography";
				case "TO": return "Tondonero";
				case "TOKO": return "Tokotype";
				case "TOPP": return "Toppan Printing Co., Ltd.";
				case "TPDP": return "Type Department";
				case "TPMA": return "typoma";
				case "TPOP": return "Tipos Pereira Type Foundry";
				case "TPSP": return "Type Supply";
				case "TPTA": return "TPTQ Arabic";
				case "TPTC": return "Test Pilot Collective";
				case "TPTQ": return "Typotheque";
				case "TR": return "Type Revivals";
				case "TRAF": return "Traffictype";
				case "TREE": return "Treeflow";
				case "TS": return "TamilSoft Corporation";
				case "TSPC": return "Typespec Ltd";
				case "TSTY": return "Torleiv Georg Sverdrup";
				case "TT": return "TypeTogether";
				case "TTC": return "Tribby Type Co.";
				case "TTG": return "Twardoch Typography";
				case "TTY": return "Tipotype";
				case "TY": return "Typocalypse";
				case "TYCU": return "TypeCulture";
				case "TYFR": return "typographies.fr";
				case "TYME": return "type me! Font Foundry";
				case "TYPA": return "Typadelic";
				case "TYPB": return "Type Brut";
				case "TYPE": return "Type Associates Pty Ltd";
				case "TYPO": return "Typodermic";
				case "TYPR": return "Type Project";
				case "TYRE": return "typerepublic";

				// U
				case "UA": return "UnAuthorized Type";
				case "UBER": return "übertype";
				case "UKUK": return "Ultra Kühl";
				case "ULA": return "Montserrat Typeface";
				case "UNDS": return "Underscore Type";
				case "UNDT": return "ÜNDT";
				case "UNIC": return "Unicode Consortium";
				case "URW": return "URW++";
				case "UT": return "Unitype Inc";

				// V
				case "VINT": return "Vinterstille";
				case "VJ": return "eDESIGNzone";
				case "VKP": return "Vijay K. Patel";
				case "VLKF": return "Visualogik Technology & Design";
				case "VLNL": return "VetteLetters.nl";
				case "VMT": return "VMType";
				case "VOG": return "Martin Vogel";
				case "VOL": return "Bernd Volmer";
				case "VOLT": return "volto.one";
				case "VRED": return "Vred Letters";
				case "VROM": return "Vladimir Romanov";
				case "VS": return "VorSicht GmbH";
				case "VT": return "VISUALTYPE SRL";
				case "VTF": return "Velvetyne Type Foundry";
				case "VTP": return "Quang Manh Nguyen";
				case "VTYP": return "(v) design";

				// W
				case "WAFO": return "Walden Font Co.";
				case "WALA": return "Fontwala";
				case "WASP": return "Wasp Barcode Technologies";
				case "WEI": return "Wei Huang";
				case "WILL": return "Willerstorfer Font Foundry";
				case "WL": return "Writ Large Fonts";
				case "WM": return "Webmakers India";

				// X
				case "XFC": return "Xerox Font Services";
				case "XOTH": return "Xoth Morello";
				case "XYZ": return "XYZ Type LLC";

				// Y
				case "Y&Y": return "Y&Y, Inc.";
				case "YDI": return "YOON Design Group";
				case "YDS": return "Yellow Design Studio";
				case "YN": return "Yanone";
				case "YOFF": return "Your Own Font Foundry";
				case "YOKO": return "Yokokaku";
				case "YOUR": return "YourFonts.com";
				case "YWFT": return "YouWorkForThem";

				// Z
				case "z01": return "Jiangxi ZoomlaCMS Soft Co. LTD";
				case "ZANE": return "Unrender";
				case "ZeGr": return "Zebra Font Factory";
				case "zeta": return "Tangram Studio";
				case "ZSFT": return "Zsoft";
			}
			return id;
		}
	}
}
